### PR TITLE
PostgreSQL 10 compatibility

### PR DESCRIPTION
**Pull request by darthunix**
Added PostgreSQL 10 compatibility (no new features, only that are supported by 9.6):

* fixed sequence support.
* fixed problems in constraints when table's name is a reserved word (like "order") and shoul be in '"'
* fixed a problem when trigger function lies in schema different from table's one
* fixed trigger test for non-public schema

### CODE REVIEW

**Comment by jmafc** [comment]
What is the `.idea/vcs.xml` file for?

It would be helpful if you could provide a regression test for the issue with constraints and reserved words.

I assume that you tested the sequence part of the change against PG 10, right?  (I just installed it last Friday and didn't yet have a chance to run Pyrseas tests against it).

The change to `pyrseas/dbobject/constraint.py` uses `hasattr`. I've just spent several weeks trying to remove that kind of code: attributes should be initialized in the constructor so we don't have to use `hasattr`. If you need to distinguish between a dict and a list you can use `isinstance`, but I would prefer to correct the root problem if possible.

It may be best to split this pull request into three: sequence, constraint and trigger.

**Comment by jmafc** [comment]
Aside: the fix for non-`public` schema triggers reminded me of issue #165. Need to review fix applicability there.

**Comment by darthunix** [comment]
1. `.idea/vcs.xml` is my fault. I forgot to add Pycharm's `.idea` folder to git ignore
2. Ok, I'll add tests about reserved words
3. Yes, sequence have been tested on pg10. In fact this pack of changes were tested on my weird db schema for pg10. And it is a minimum change to make Pyrseas serialize pg schema to yaml and create migrations for pg10.
4. I'll think about refactoring `constraints.py` to fix the core of a problem though this module is a little tricky
5. I don't like the idea to split this pull into three different as non of them separately would make Pyrseas work with pg10. But if you insist I divide my new pull request.
I'll work on new pull request on this weekends.

**Comment by jmafc** [comment]
Well, if it's any consolation, there are still three unit tests (and all functional tests) that fail against PG 10 after applying your Sequence changes. The tests are `ColumnToMapTestCase.test_column_defaults`, `DomainToMapTestCase.test_domain_default` and `TableToMapTestCase.test_map_table_quoted`. I'm not sure your other changes would fix those.
In any case, I'm going to commit your changes to `pyrseas/dbobject/table.py` separately and probably also your Trigger changes.

**Comment by jmafc** [comment]
I have committed the sequence support and the trigger changes, so the only real thing left is the constraint changes. It's probably better if you close this PR and submit a separate one for that.

 It's not a question of refactoring `constraint.py` but rather determining why sometimes you seem to see a list and sometimes a dict. If I understand correctly, we're dealing with the `columns` attribute of a UniqueConstraint (or a PrimaryKey). That should *always* be a list because (in SQL, but not in the relational model) the order of the attributes is significant. So if in some place it's showing up as a dict, it's wrong and *that* should be corrected.

**Comment by jmafc** [comment]
@darthunix I checked the problem with constraints on a table using a reserved word by issuing the following SQL against a PG 9.4 database: `CREATE TABLE "order" (c1 integer UNIQUE, c2 text)`.  The error occurs in `pyrseas/dbobject/table.py` in `ClassDict.link_refs` when we attempt to assert that the constraints schema.table combinations exists in the `ClassDict` dictionary.

This problem appears to have existed for quite some time and is not related to PG 10 compatibility. Therefore, since I believe the other parts of the PR have been addressed elsewhere, I suggest that we close this PR and instead open an issue as described by the test above.

**Comment by jmafc** [comment]
See issue #177.

**Pull request closed without merging**
