### PR TITLE
implement diff_map for triggers

### PR DESCRIPTION
**Pull request by reedstrm**
Had a case of triggers changing procedure as well as events. This solves it. Haven't extended tests to cover.

### CODE REVIEW

**Comment by jmafc** [comment]
@reedstrm The CI tests failed. I only took a quick look at the code and the failures, but I think you have to add the `diff_privileges` and `diff_description` that are in the `DbObject.diff_map` method to your new `Trigger.diff_map`.

**Comment by reedstrm** [comment]
Ah, I see I overrode the parent class method, but didn't handle the cases it does, as well. I'll take a look at it. Had a bit of a problem getting all the tests to run locally - there's several assumptions about the local environment (e.g. pg_dump is not named pg_dump95 on my ubuntu install) that caused errors that masked the legit ones.

**Comment by reedstrm** [comment]
I set TRAVIS=true and got the tests to run locally as well (w/ the setup from .travis.yml)

**Comment by jmafc** [comment]
`pg_dumpNN` came out of the desire to run tests against multiple PG installations and the fact that different platforms place the `pg_dump` executable in different locations and allow you to invoke it in different ways. I noticed this hasn't yet been documented in out testing checklist. Maybe we should implement a (default) alternative for running the tests using just `pg_dump` (the one in your PATH) and use the `pg_dumpNN`s only for running within tox.

**Pull request merged**
